global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'ppa-dotnet-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['ppa-dotnet-api:80']

  - job_name: 'ppa-node-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['ppa-node-api:3030']

  - job_name: 'ppa-go-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['ppa-go-api:8080']
